@startuml
:user provides all animals to shelter;
:system retrieves the animals;
if (animal) then (sorted)
:system retrieves the animals;
:sortAnimal;
else (animal) (clean)
:system retrieves the animals;
:ListAnimal;

@enduml