@startuml
User -> AnimalShelterApp : inputs name
AnimalShelterApp -> AnimalService : findAnimal(name)

AnimalService -> AnimalRepository : getAnimals()
AnimalService <-- AnimalRepository : List<Animal>

alt Sorting by name
AnimalService -> AnimalService : sortAnimalsByName(List<Animal>)

else (no)
AnimalService -> AnimalService : :Error: can not found  animals by name;

end

AnimalShelterApp <-- AnimalService : void
User <-- AnimalShelterApp : OK message
@enduml