@startuml
User -> AnimalShelterApp : input List<Animal>


AnimalShelterApp -> AnimalService : addAnimal
AnimalShelterApp <-- AnimalService : void

AnimalService -> AnimalRepository : addAnimal
AnimalRepository --> AnimalService : error message



AnimalService -> AnimalRepository : getAnimals()
AnimalService <-- AnimalRepository : List<Animal>



User <-- AnimalShelterApp : ok

@enduml