@startuml

User -> AnimalShelterApp : inputs name
User -> AnimalShelterApp : inputs all animals

AnimalShelterApp -> AnimalService : getAllAnimalsSortedByName(SortType: name)
AnimalService -> AnimalRepository : getAllAnimals()
AnimalService <-- AnimalRepository : List<Animal>

AnimalShelterApp <-- AnimalService : List<Animal>
User <-- AnimalShelterApp : OK message

@enduml

@startuml

start

: user provides getAllAnimals method;
:print list of getAnimals;
end;
@enduml

@startuml
user--> AnimalShelterApp : input to get list of animals
AnimalShelterApp --> AnimalService : getListOfAnimals()
AnimalService --> AnimalRepository : getAnimals()
AnimalService <-- AnimalRepository : list<Animal>
AnimalShelterApp <-- AnimalService : list<Animal>
user <-- AnimalShelterApp : list<Animal>

@enduml