@startuml


User -> AnimalShelterApp : inputs name or age

AnimalShelterApp -> AnimalService : treatAnimal;

AnimalService -> AnimalRepository : getAnimals()
AnimalService <-- AnimalRepository : List<Animal>

alt treatAnimalsByName
AnimalService -> AnimalService : treatAnimalsByName(List<Animal>)


else  treatAnimalsByAge
AnimalService -> AnimalService : treatAnimalsByAge(List<Animal>)
end

AnimalService --> AnimalShelterApp : void

User <-- AnimalShelterApp : OK message

@enduml