@startuml

User -> AnimalShelterApp : inputs name or age
AnimalShelterApp -> AnimalService : findAnimal()


AnimalService -> AnimalRepository : getAnimals()



alt finding by name
AnimalService -> AnimalService : findAnimalsByName(List<Animal>)


AnimalService -> AnimalRepository : getAnimals()


alt finding by ID
AnimalService -> AnimalService : findAnimalsByID(List<Animal>)
else (no)
AnimalService -> AnimalService : :Error: can not found  animals by name;
end
AnimalService <-- AnimalRepository : List<Animal>

AnimalService --> AnimalShelterApp

User <-- AnimalShelterApp : OK message
@enduml