@startuml
User -> AnimalShelterApp : input List<Animal>
AnimalShelterApp -> AnimalService : sortAnimals
AnimalService --> AnimalShelterApp : List<Animal>


AnimalShelterApp -> AnimalRepository : returnAllAnimal


AnimalShelterApp <-- AnimalRepository : returnAllAnimal

User <-- AnimalShelterApp : OK message


@enduml